### ISSUE TITLE
More than one objects in image and Feature Vector for Image Retrieval

### ISSUE THREAD

**Issue by Paul0M** [JDAI-CV/DCL#15]
Nice work!
wonder 2 things:
1st:
DCL focuses on the detailed discriminant part, then extract features, and then do classification. So if there are more than one objects [**dog and cat**] in image, have you tested the impact on DCL? 
2nd:
Have you extented DCL feature vector for Image Retrieval?
since classifier layer is 2048->num_classes and there are many SKUs in e-commerce, wondering how to bridge the gap of the former two?
If there are 1 billion SKUs, just using a small and finite part of the SKUs may not good enough. such as 2048->1000SKUs, or 20480->10000SKUs

**Comment by akira-l** [comment]
Thanks for your attention and raising two interesting concerns.

The prerequisite needs to be clear that DCL is targeted to fine-grained classification tasks as the paper proposed. The idea is also helpful in some general classifications. Due to the specific goal, we have not tried DCL in other domains. 

For the first question, in my view, it's a typical detection task, rather than classification, nor fine-grained. From the perspective of raising the problem, it is a bit strange to set [dog&cat] into one category. If the dataset has n isolated categories and m objects in each image, n^m labels are required for classification. 

For the second question, the retrieval task is also out of scope discussed in the paper and original intention of DCL. It might be useful in the retrieval and we are also glad to see further applications. Moreover, for the enormous amount of categories, it seems not economical to use one fc layer for massive categories.  From the point of classification, applying hierarchical labels seems more efficient. From the retrieval, matric learning seems better as in face recognition and re-id. From the engineering practice. some indexing or database technologies seem more practicable.

**Comment by Paul0M** [comment]
thanks for your reply.
yes, it's good to use [detection->fine-grained classification] or multi-label classification. one of my concerns is: if training with multi-label, aa image with a dog and a cat, with label [1,1], I think the model may not perform well with an image which contains just a dog or cat during inference, since the supervision infomation only contains image-level label and no bbox.

For the second question, since DCL focus on details in stead of the global, i guess it may outperform matric learning :)
